name: sciencesimpact
favicon: null
layout_spectrum: 0.50355
typography_spectrum: 0.50387
title: IMPACT @ Griffith Sciences
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e34a52'
    - '#ffffff'
    - '#f4b9bc'
    - '#f8dcdd'
    - '#ec888d'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.3222104446031153
  rhythmicContrast: 0.5
purpose: []
