name: sciencesimpact
favicon: null
layout_spectrum: 0.8258634738158435
typography_spectrum: 0.8932904042303562
title: IMPACT @ Griffith Sciences
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.1362432506866753
  lightness: 0.5884317723102868
  saturation: 0.3222104446031153
  rhythmicContrast: 0.8085353903006762
purpose: []
